### ISSUE TITLE
Missing Release file

### ISSUE THREAD

**Issue by rbowden91** [cs50/libcs50#85] opened 2017-06-27 16:25 UTC
In Bash for Windows (which should basically just be Ubuntu?), I'm getting this after trying the apt-get update step:

W: The repository 'http://ppa.launchpad.net/cs50/ppa/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/cs50/ppa/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

In the meantime I installed from source.

**Comment by kzidane** [comment] 2017-06-27 16:37
Thanks for reporting! I think I probably know what the problem is. Will fix asap!

**Comment by kzidane** [comment] 2017-07-27 19:19
Just manually re-packaged and deployed for Xenial. This should be fixed now. The package should be auto-deployed for Xenial starting next release per https://github.com/daveyproctor/libcs50/pull/1. I have tested from a Xenial container and it seems to work. Please let me know if you're still experiencing this problem! Thank you!

**Closed by kzidane** 2017-07-27 19:19 UTC
